### ISSUE TITLE
Target column is missing rows

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord-box3/tn-converter-app#17]

**Comment by elsylambert** [comment]
Not seeing this issue. The columns on both sides are even.

**Comment by elsylambert** [comment]
@manny I am referencing this issue to ask about missing rows:
Using one of your Repositories es-419_tq, found that 2Jn has missing rows on both sides(Missing rows in Target and blank rows in source).
Can you please verify if this is the same bug or is caused by something new.

**Comment by mannycolon** [comment]
@elsylambert Do you mind testing the bug referenced above using this preview build to see if it got fixed? Do you have more details about how you determined there were missing source rows?

https://deploy-preview-71--tn-converter-app.netlify.app

**Comment by elsylambert** [comment]
Verified in https://deploy-preview-71--tn-converter-app.netlify.app
Comparing Rows in Repo vs in app: Example from 3jn.
- Verse 1
![Screen Shot 2021-03-23 at 12.51.50 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d0a5aeb1-ad33-460d-acd7-9ff78e001c44)
- Missing 4th question in the app
![Screen Shot 2021-03-23 at 12.52.11 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/b35c4ea2-bfd2-4205-a9f8-d3139dfaa6cd)
- Verse 9
![Screen Shot 2021-03-23 at 12.53.25 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/8ede48d6-5ec8-495c-8416-d6822c3bab0b)
- Missing last 2 questions in the app.
![Screen Shot 2021-03-23 at 12.53.46 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/6cf691c3-4fd7-47b5-80aa-60fbd2d8d985)
-Verse 11 has two questions in the app
![Screen Shot 2021-03-23 at 12.54.41 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/bc93e13f-02d1-42fb-bf9f-5e60047b7417)
- Only one in the Repo
![Screen Shot 2021-03-23 at 12.54.58 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ba3bfdc0-fbed-4468-835d-b785b578f947)
- Verse 13 is missing in the app.

**Comment by cckozie** [comment]
Tested all English books to ensure that the source and target rows are equal.
Continuing to test same on non-English books.
Also need more testing of comparing rows in the converter to the DCS md file.

**Comment by cckozie** [comment]
There are still some missing target rows. I think the problem appears when there are questions defined in the target language md file and there are no questions defined for that chapter/verse in the English.

Here are the examples from 1JN: (comparing app data to https://git.door43.org/manny_colon/es-419_tq/src/branch/master/1jn)

2:1 ¿Por los pecados de quién es que fue el sacrificio de Jesucristo? Jesucristo es el sacrificio por los pecados de todo el mundo.
2:1 ¿Cómo sabemos si conocemos a Jesucristo? Nosotros sabemos que conocemos a Jesucristo cuando guardamos sus mandamientos.
3:23 ¿Qué es lo que Dios le ha dado a los creyentes para que ellos sepan que Dios permanece en ellos? Dios le ha dado a los creyentes el Espíritu para que ellos sepan que El permanece en ellos.
5:1 ¿Cómo podemos demostrar que amamos a Dios? Nosotros demostramos que amamos a Dios cuando guardamos sus mandamientos.
5:20 ¿De qué se deben guardar los creyentes? Los creyentes se deben guardar de los ídolos.

**Comment by cckozie** [comment]
The English source now contains verse spans so we'll need to wait until the app has been enhanced to handle them before this can be tested further.

**Comment by BincyJ** [comment]
Based on the fix for https://github.com/unfoldingWord-box3/tn-converter-app/issues/80, this should be resolved. @elsylambert can you please retest to confirm? Thanks.

**Comment by elsylambert** [comment]
Tested on the latest build on July 20. Tested using Katalon script- Test all row exist for tN and tQ. Not seeing missing rows. Looks good.
