### ISSUE TITLE
There are missing notes in the target columns that are found in the markdown notes in the repo

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord-box3/tn-converter-app#25]

**Comment by mannycolon** [comment]
# List of missing items

- то делаем из Него лжеца https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/01/10.md
- Общая информация https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/01.md
- А то, что мы знаем Его https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/03.md
- кто соблюдает Его слово https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/05.md
- Связующее утверждение: https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/07.md
- Общая информация: https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/09.md
- тот находится во тьме https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/11.md
- Отцы, пишу вам https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/13.md
- Не любите этот мир https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/15.md
- проходит https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/17.md
- Они вышли от нас https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/19.md
- Only checked until chapter 2.

## Wrong order

- https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/04.md
- https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/06.md
- https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/08.md
- https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/12.md
- https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/14.md
- https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/16.md
- https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/18.md

## Extra items in the target that arent found in the English source notes

- https://git.door43.org/ru_gl/ru_tn_1lv/src/branch/master/1jn/02/20.md ???

**Comment by elsylambert** [comment]
@mannycolon  for the "Extra items in the target which are not in English Source notes", how are those notes handled? I do not see extra target notes in 1 jn(ru) Project. Kindly suggest.

**Comment by mannycolon** [comment]
@elsylambert That's one of the questions I have for @birchamp

**Comment by cckozie** [comment]
I'm looking at https://git.door43.org/mxaln/ru_col_tn_L2/src/branch/master/col/
In DCS I see tNs all the way to 4:18, but in the app I'm only seeing those to 1:28.
@mannycolon - Is this a legitimate project?
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/8ef3b646-e5b6-49d3-9a35-2c7478a3f58c)

**Comment by mannycolon** [comment]
@cckozie This project seems to be in HTML even though the files are in markdown

check https://git.door43.org/mxaln/ru_col_tn_L2/raw/branch/master/col/02/01.md

**Comment by mannycolon** [comment]
Chapter 1 follows proper Markdown markup, but chapter 2 through 4 use HTML markup

**Comment by cckozie** [comment]
Yes, I see that is a problem with some of the chapters in eph as well for that DCS user name.
I wrote up #57 to inform the user of the data problem, if desired.
Moving back to In QA

**Comment by cckozie** [comment]
I'm not seeing any missing notes in the target columns except where there are more GL notes than English notes. This should be handled by #51.

**Comment by elsylambert** [comment]
Looks good with the latest changes by #51.
