### ISSUE TITLE
EPIC: Handle 3x3 GLs 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord-box3/tn-converter-app#31]
- [x] 1st iteration: Validate English content
- [ ]   2nd iteration: Add 3x3 GLs (Hindi, Kannada, ES-419, Russian)
Allow the 4 GLs in the 3x3 strategy to use the validator on their own repos.

**Comment by RobH123** [comment]
Ok, I did some refactoring to make sure that the languageCode is correctly passed all the way down and so hopefully [this demo](https://unfoldingword.github.io/uw-content-validation/#/GL%20Book%20Package%20Checker%20Demo?id=glbookpackagecheck) might be working now, i.e., the hard work has been done. Just need to update the app UI now I think.
