### ISSUE TITLE
Handle multiple Gateway languages

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord-box3/tn-converter-app#37]

**Comment by mannycolon** [comment]
Use the following repos in order to test this issue:

https://git.door43.org/manny_colon/es-419_tn
https://git.door43.org/manny_colon/pt-br_tn

Feel free to fork them.

**Comment by elsylambert** [comment]
Tested with Forked Repos for Spanish and Portuguese. Multiple GL projects work fine.
