### ISSUE TITLE
Add a save backup option

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord-box3/tn-converter-app#46]
Add a "Save backup" option for the user to save the json.  Prompt user to save when closing tab or changing projects

**Comment by mannycolon** [comment]
@birchamp ^^

**Comment by cckozie** [comment]
1. I think the term "Download Backup" will be confusing to users and "Save Backup" as specified would be better.
2. I opened a project and made a change in it. I was not prompted to save when changing projects.
3. I also was not prompted to save when closing the tab after modifying a project.

**Comment by mannycolon** [comment]
1. I will change it to "Save Backup" but the reason why I put "Download Backup" is because it may make the user think their project data is being backed up on the cloud, in a database, or on DCS and not downloaded locally in a file.

**Comment by mannycolon** [comment]
@cckozie @birchamp Please read above

**Comment by mannycolon** [comment]
2. Resolved
3. Newer browsers do not allow to customize the prompt shown before closing the tab after modifying a project. Thus we are left with the following prompt...


<img width="1196" alt="Screen Shot 2020-10-02 at 12 28 29 PM" src="https://user-images.githubusercontent.com/17072300/94946910-cde1a280-04aa-11eb-809e-da4751281e83.png">

**Comment by birchamp** [comment]
I like that @mannycolon. I think we need something similar in tC Create.

**Comment by mannycolon** [comment]
Important details about point number 3

> To combat unwanted pop-ups, some browsers don't display prompts created in `beforeunload` event handlers unless the page has been interacted with. Moreover, some don't display them at all.

https://dev.to/jeddtony/prevent-window-from-closing-in-react-js-4mbh

**Comment by mannycolon** [comment]
If the user doesn't save a backup the prompt will show up, if the user clicks save backup and doesn't make any changes to the project then the prompt won't show up because it has already been saved. However, if the user changes something then the prompt will show up again. Also, a checkmark will be shown in the "Save backup" button.

**Comment by elsylambert** [comment]
Looks good in the latest. Save Backup option is working fine-
 It downloads on the local machine. 
The button is enabled once the changes are done. 
The prompt comes up when user leaves the project without saving, either by closing tab or switching to another project.
