### ISSUE TITLE
Project List lost unexpectedly when closing and reopening the app 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord-box3/tn-converter-app#48]

**Comment by mannycolon** [comment]
On Chrome, open a project then go to the projects list. Should have at least one project on the projects page.  Type COMMAND + W (On Mac) to close the tab and SHIFT + COMMAND + T (On Mac) to reopen the last closed tab and should see all projects previously created without losing any like before this fix

**Comment by elsylambert** [comment]
Using the shortcut keys on Mac, I am able to close and reopen a tab in chrome, but the tab stays blank as shown in the screenshot till I switch to another tab and come back to the reopened tab.

![Screen Shot 2020-09-28 at 12.05.52 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/250259e7-1cf2-4d4b-b409-2fd757c10d8a)
Are you seeing this? @mannycolon 
After reopening, I am seeing my Projects List which looks fine.

**Comment by mannycolon** [comment]
Very strange, it works fine on my end

**Comment by elsylambert** [comment]
The blank screen in not related to the app, but the browser. It is happening with the other tabs as well.
I am passing this issue as I am not losing Project list when closing the tab.
