### ISSUE TITLE
The file gets corrupted when the back button is clicked while loading a file

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord-box3/tn-converter-app#70]
Steps:
- select a valid Repo and select a book to Open. I opened Genesis first.
- As you see the book loading, Click the Back button.
- Now select another book to load(eg. Titus). Note that you can see the loader showing both books loading up together.
- When the file is opened, source and Target shows different books.
![Screen Shot 2021-03-23 at 12.07.02 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/4c767e18-d249-4d25-860d-33719b61af21)

**Comment by BincyJ** [comment]
@elsylambert can you retest this?

**Comment by cckozie** [comment]
The user is now locked out of performing any activity in the app until the project gets fully loaded. This prevents the file from getting corrupted by "simultaneously" loading two projects.
I wrote up issue #81 while testing this problem, but I see it as a lower priority.

**Comment by elsylambert** [comment]
User does not have an option to stop loading the file except for closing the app. This solves the problem of file corruption. Seeing the Verbiage changed as "Processing ". Looks good.
