### ISSUE TITLE
Duplicate sequential TQs should be combined into a verse range.

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord-box3/tn-converter-app#73]
NOTE: This needs to be re-evaluated after #80 is complete.

Users want to have duplicate TQs combined.  If a TQ MD file is the same for sequential verses then that TQ should be combined and given a verse range when it's converted to TSV. In the example below, since the same question and answer appear in Acts 1:21 and 22 the MD-TSV Converter should combine those into a single question with '1:21-22' in the Reference column.  (verse ranges are to be formatted [chapter]:[verse]-[verse] per [our TSV spec](https://forum.door43.org/t/parascriptural-tab-separated-value-format-specification-v2/870))

![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/95bb0dac-4325-4a15-b9a7-8ba6238124b2)

**DoD**: Importing a repo with duplicate, sequential MD TranslationQuestions will result in a single row in the TSV with the appropriate verse range in the Reference column.

**Comment by mannycolon** [comment]
@birchamp What is a good project to use to test this?

**Comment by birchamp** [comment]
@mannycolon  Acts is a good one, but I just realized that this has changed now that we're doing the checkmarks. We don't need to combine the source side anymore.
