### ISSUE TITLE
Source row are replaced with target rows after project export and then  dragging target check

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-box3/tn-converter-app#76]
To replicate:
Start a new project
Export the project
Drag a target verse to a new location
Note that the source rows have been replaced with target rows

https://images.zenhubusercontent.com/287125656/ac15d1e2-be1e-4144-a239-b58aaa5cf439/issue_76.mp4

**Comment by cckozie** [comment]
No longer seeing this problem.

**Comment by elsylambert** [comment]
This issue is fixed in the latest.
