### ISSUE TITLE
Allow users to include/exclude rows

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord-box3/tn-converter-app#80]
Because a number of English questions have been deleted, users need to be able to include a particular target record that is not on the source side.

![MD_TSV_Conv_exclude.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/5558d1fd-fad4-41eb-8172-d644ad209c52)

Add in a column titled "Include?" Fill the column with checkboxes that are checked by default. Any row that is completely empty or not checked should not be included in the export. Any included row that has target text should export the target, and any included row that only has the English should export the English for that row.

When the user excludes (unchecks) a row that has both source and target text:

- strikeout and gray out the target side
- blank the source side of the excluded row
- drop the source side text to its own row with blank target fields.

Excluding a row with only source text or only target text but not both will simply grey and strikeout any target text if there is any.

https://images.zenhubusercontent.com/287125656/fc0b0b16-536a-4a46-8235-4fc31a3852a8/screencast_2021_04_15_12_49_59.mp4

| English Source  | Included? | Target text |    | Output |
| --------------- | ---------- | ----------- | - | ------- |
| X |  X | X | | Target text |
| X |    | X | | no row |
| X |  X |  | | English text |
| X |    |   | | no row |
|  |  X | X | | Target text |
|   |    | X | | no row |
|   |  X |   | | no row |

DoD:
---
There are checkboxes available to the user that are checked by default. Any checked row with text in either the source or target will be included in the exported TSV.

**Comment by mannycolon** [comment]
@birchamp LGTM

**Comment by cckozie** [comment]
There is no strikeout or gray out in tN projects, but those are not in the DoD. Otherwise this looks good.
Wrote up #92 for that difference.

**Comment by elsylambert** [comment]
This works as expected in the latest as tested on July 15, 2021.
