### ISSUE TITLE
Drag and Drop action: Causing data loss when using "Included" Checkbox

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord-box3/tn-converter-app#96]
Tested in the new https://deploy-preview-95--tn-converter-app.netlify.app/

Drag and Drop action: There are two issues found in when Drag and drop was done for a row.

1. When a row is dragged to the very bottom of the page(end of the rows -10 rows per page) and then dropped, the row goes into a different row(instead of the original row from where it was dragged).
When I unchecked the Include checkbox for a different row, another row got unchecked and saw that the row completely disappeared from the page as opposed to a strikethrough.
https://images.zenhubusercontent.com/287125656/23d74db6-2332-404d-9450-028be1944ac6/drag_drop_640.mp4
2. When a row is dragged to the very bottom of the page(end of the rows -10 rows per page) and then dropped, the row goes into a different row(instead of the original row from where it was dragged).
When I unchecked the Include checkbox to correct it, it unchecked another row, which cannot be checked back and we see data lost when we reopen the project even when we do not save the changes.

https://images.zenhubusercontent.com/287125656/9852f87f-dc12-4d6b-a493-f80d684a2043/drag_640.mp4

**Comment by mannycolon** [comment]
@elsylambert I fixed issue #1, However, issue #2 seems to me its expected behavior.  

When a row is dragged to the very bottom of the page(end of the rows -10 rows per page) and then dropped, the row should go into the very last position it hovered over. This has always been that way.

**Comment by elsylambert** [comment]
Note:  Clear cache with the latest MD-TSV Converter build, which means old projects will not be visible in My Projects page.

**Comment by elsylambert** [comment]
The issue with the Drag and drop and Include checkbox has been fixed as tested on July 13, 2021.
