### ISSUE TITLE
UI issue: Netlify drawer overlaps the footer navigation bar

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord-box3/tn-converter-app#98]
Netlify drawer overlaps the footer navigation bar.![Screen Shot 2021-07-06 at 12.34.09 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/98776511-94df-46f7-874f-8e2b8b088fb4)

**Comment by mannycolon** [comment]
@elsylambert We have no control over the Netlify drawer, which is added by Netlify only on deploy previews. It will not be shown in production (https://tn-converter-app.netlify.app/)  [#98](https://github.com/unfoldingWord-box3/md-converter-app/issues/98)

**Comment by elsylambert** [comment]
Closing this issue based on Manny's comment above.
